"""empty message

Revision ID: 0b920976a60a
Revises: 7fd18dfc2368
Create Date: 2024-07-07 23:56:54.293926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b920976a60a'
down_revision: Union[str, None] = '7fd18dfc2368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'desc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
