"""empty message

Revision ID: 17f1c38e922e
Revises: 2d4d558d9957
Create Date: 2024-07-01 13:57:35.691544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f1c38e922e'
down_revision: Union[str, None] = '2d4d558d9957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('admin_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'parents', 'admins', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parents', type_='foreignkey')
    op.drop_column('parents', 'admin_id')
    # ### end Alembic commands ###
