"""empty message

Revision ID: 1b42570c7d7b
Revises: 
Create Date: 2024-07-30 00:02:56.282064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b42570c7d7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('motDePasse', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_nom'), 'admins', ['nom'], unique=False)
    op.create_index(op.f('ix_admins_prenom'), 'admins', ['prenom'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('titre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('motDePasse', sa.String(), nullable=True),
    sa.Column('pays', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('codeParental', sa.String(), nullable=True),
    sa.Column('nbre_profil', sa.Integer(), nullable=True),
    sa.Column('historique_video', sa.String(), nullable=True),
    sa.Column('maxProfilEnfant', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('email')
    )
    op.create_table('series',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('titre', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('nb_saisons', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enfants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pseudo', sa.String(), nullable=True),
    sa.Column('image_profil', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('code_pin', sa.String(), nullable=True),
    sa.Column('historique_video', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saisons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('titre', sa.String(), nullable=True),
    sa.Column('nb_episodes', sa.Integer(), nullable=True),
    sa.Column('serie_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tempsEcrans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('joursA', sa.String(), nullable=True),
    sa.Column('heuresD', sa.Time(), nullable=True),
    sa.Column('heuresF', sa.Time(), nullable=True),
    sa.Column('enfant_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['enfant_id'], ['enfants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('titre', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duree', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('type_Source', sa.Enum('YOUTUBE', 'DAILYMOTION', 'ANIMESAMA', 'UPLOAD', name='type_source_enum'), nullable=True),
    sa.Column('couverture', sa.String(), nullable=True),
    sa.Column('type_video', sa.Enum('FILM', 'EPISODE', name='type_video_enum'), nullable=True),
    sa.Column('admin_id', sa.String(), nullable=True),
    sa.Column('saison_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['saison_id'], ['saisons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorie_video',
    sa.Column('categorie_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('categorie_id', 'video_id')
    )
    op.create_table('enfant_video',
    sa.Column('enfant_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('like', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['enfant_id'], ['enfants.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('enfant_id', 'video_id')
    )
    op.create_table('parent_video',
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('like', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_video')
    op.drop_table('enfant_video')
    op.drop_table('categorie_video')
    op.drop_table('videos')
    op.drop_table('tempsEcrans')
    op.drop_table('saisons')
    op.drop_table('enfants')
    op.drop_table('series')
    op.drop_table('parents')
    op.drop_table('categories')
    op.drop_index(op.f('ix_admins_prenom'), table_name='admins')
    op.drop_index(op.f('ix_admins_nom'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
