"""empty message

Revision ID: 2d4d558d9957
Revises: d6a202fb8bc4
Create Date: 2024-07-01 13:31:35.781255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d4d558d9957'
down_revision: Union[str, None] = 'd6a202fb8bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('titre', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duree', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('type_video', sa.Enum('FILM', 'EPISODE', name='type_video_enum'), nullable=True),
    sa.Column('admin_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enfant_video',
    sa.Column('enfant_id', sa.String(), nullable=True),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('like', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['enfant_id'], ['enfants.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], )
    )
    op.drop_table('video')
    op.drop_constraint('parents_admin_id_fkey', 'parents', type_='foreignkey')
    op.drop_column('parents', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('admin_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('parents_admin_id_fkey', 'parents', 'admins', ['admin_id'], ['id'])
    op.create_table('video',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('titre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duree', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_video', postgresql.ENUM('FILM', 'EPISODE', name='type_video_enum'), autoincrement=False, nullable=True),
    sa.Column('admin_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name='video_admin_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='video_pkey')
    )
    op.drop_table('enfant_video')
    op.drop_table('videos')
    # ### end Alembic commands ###
