"""empty message

Revision ID: 38b2543e6ec9
Revises: c2839a9a4519
Create Date: 2024-07-03 12:10:57.630362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b2543e6ec9'
down_revision: Union[str, None] = 'c2839a9a4519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enfant_video', sa.Column('taille', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enfant_video', 'taille')
    # ### end Alembic commands ###
