"""empty message

Revision ID: 3ab1687f5a77
Revises: 711363a9d8c6
Create Date: 2024-07-07 02:04:23.809005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab1687f5a77'
down_revision: Union[str, None] = '711363a9d8c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admins', ['contact'])
    op.create_unique_constraint(None, 'parents', ['email'])
    op.create_unique_constraint(None, 'parents', ['contact'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parents', type_='unique')
    op.drop_constraint(None, 'parents', type_='unique')
    op.drop_constraint(None, 'admins', type_='unique')
    # ### end Alembic commands ###
