"""empty message

Revision ID: 40196625db7d
Revises: 205c03dc4404
Create Date: 2024-07-03 15:57:02.194792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40196625db7d'
down_revision: Union[str, None] = '205c03dc4404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'desc')
    # ### end Alembic commands ###
