"""empty message

Revision ID: 4e26ea428ed9
Revises: 3ab1687f5a77
Create Date: 2024-07-07 02:18:31.265020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e26ea428ed9'
down_revision: Union[str, None] = '3ab1687f5a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('parents_admin_id_fkey', 'parents', type_='foreignkey')
    op.drop_column('parents', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('admin_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('parents_admin_id_fkey', 'parents', 'admins', ['admin_id'], ['id'])
    # ### end Alembic commands ###
