"""empty message

Revision ID: 721aa00a139d
Revises: 4ee61522804d
Create Date: 2024-07-07 03:19:19.357098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721aa00a139d'
down_revision: Union[str, None] = '4ee61522804d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tempsEcrans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('joursA', sa.String(), nullable=True),
    sa.Column('heuresD', sa.Time(), nullable=True),
    sa.Column('heuresF', sa.Time(), nullable=True),
    sa.Column('enfant_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['enfant_id'], ['enfants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tempsEcrans')
    # ### end Alembic commands ###
