"""empty message

Revision ID: 864b8e0cf33b
Revises: 10d28064dfbe
Create Date: 2024-07-01 16:27:47.662864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864b8e0cf33b'
down_revision: Union[str, None] = '10d28064dfbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorie_video',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorie_video')
    # ### end Alembic commands ###
