"""empty message

Revision ID: 9145e836108d
Revises: f00d399f9319
Create Date: 2024-08-11 18:38:33.946025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9145e836108d'
down_revision: Union[str, None] = 'f00d399f9319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('temps_visionnage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'temps_visionnage')
    # ### end Alembic commands ###
