"""empty message

Revision ID: 94d205d7daaa
Revises: 1b42570c7d7b
Create Date: 2024-08-06 14:13:02.436400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d205d7daaa'
down_revision: Union[str, None] = '1b42570c7d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'views')
    # ### end Alembic commands ###
