"""empty message

Revision ID: 9c9946d3f7f4
Revises: 864b8e0cf33b
Create Date: 2024-07-02 17:38:20.801507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9946d3f7f4'
down_revision: Union[str, None] = '864b8e0cf33b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_table')
    op.add_column('admins', sa.Column('motDePasse', sa.String(), nullable=True))
    op.drop_column('admins', 'mot_de_passe')
    op.alter_column('enfants', 'image_profil',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('saisons', sa.Column('serie_id', sa.String(), nullable=True))
    op.drop_constraint('saisons_saison_id_fkey', 'saisons', type_='foreignkey')
    op.create_foreign_key(None, 'saisons', 'series', ['serie_id'], ['id'])
    op.drop_column('saisons', 'saison_id')
    op.add_column('videos', sa.Column('saison_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'videos', 'saisons', ['saison_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'saison_id')
    op.add_column('saisons', sa.Column('saison_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'saisons', type_='foreignkey')
    op.create_foreign_key('saisons_saison_id_fkey', 'saisons', 'saisons', ['saison_id'], ['id'])
    op.drop_column('saisons', 'serie_id')
    op.alter_column('enfants', 'image_profil',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('admins', sa.Column('mot_de_passe', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('admins', 'motDePasse')
    op.create_table('my_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='my_table_pkey')
    )
    # ### end Alembic commands ###
