"""empty message

Revision ID: a29ea140e4e8
Revises: 
Create Date: 2024-07-01 11:49:18.485584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a29ea140e4e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('mot_de_passe', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_nom'), 'admins', ['nom'], unique=False)
    op.create_index(op.f('ix_admins_prenom'), 'admins', ['prenom'], unique=False)
    op.create_table('saisons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('titre', sa.String(), nullable=True),
    sa.Column('nb_episodes', sa.Integer(), nullable=True),
    sa.Column('saison_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['saison_id'], ['saisons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('titre', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('nb_saisons', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('motDePasse', sa.String(), nullable=True),
    sa.Column('pays', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('codeParental', sa.String(), nullable=True),
    sa.Column('nbre_profil', sa.Integer(), nullable=True),
    sa.Column('historique_video', sa.String(), nullable=True),
    sa.Column('admin_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enfants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pseudo', sa.String(), nullable=True),
    sa.Column('image_profil', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('allocation', sa.String(), nullable=True),
    sa.Column('joursA', sa.String(), nullable=True),
    sa.Column('heuresA', sa.String(), nullable=True),
    sa.Column('code_pin', sa.String(), nullable=True),
    sa.Column('historique_video', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enfants')
    op.drop_table('parents')
    op.drop_table('series')
    op.drop_table('saisons')
    op.drop_index(op.f('ix_admins_prenom'), table_name='admins')
    op.drop_index(op.f('ix_admins_nom'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
