"""empty message

Revision ID: c3e185dca967
Revises: 721aa00a139d
Create Date: 2024-07-07 21:35:19.408543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3e185dca967'
down_revision: Union[str, None] = '721aa00a139d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_video',
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('like', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_video')
    # ### end Alembic commands ###
