"""empty message

Revision ID: d6a202fb8bc4
Revises: a29ea140e4e8
Create Date: 2024-07-01 11:57:22.845765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a202fb8bc4'
down_revision: Union[str, None] = 'a29ea140e4e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('titre', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duree', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('type_video', sa.Enum('FILM', 'EPISODE', name='type_video_enum'), nullable=True),
    sa.Column('admin_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    # ### end Alembic commands ###
